heat_template_version: 2016-04-08

description: >
  Openstack Zaqar service. Shared for all Heat services.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  ZaqarPassword:
    description: The password for Zaqar
    type: string
    hidden: true
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint


outputs:
  role_data:
    description: Shared role data for the Heat services.
    value:
      config_settings:
        zaqar::admin_password: {get_param: ZaqarPassword}
        zaqar::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri]}
        zaqar::identity_uri: {get_param: [EndpointMap, KeystoneAdmin, uri_no_suffix]}
        zaqar::debug: {get_param: Debug}
        zaqar::keystone::auth::password: {get_param: ZaqarPassword}
        zaqar::keystone::auth::public_url: {get_param: [EndpointMap, ZaqarPublic, uri]}
        zaqar::keystone::auth::admin_url: {get_param: [EndpointMap, ZaqarAdmin, uri]}
        zaqar::keystone::auth::internal_url: {get_param: [EndpointMap, ZaqarInternal, uri]}
        zaqar::keystone::auth::region: {get_param: KeystoneRegion}
        zaqar::transport::websocket::bind: {get_param: [EndpointMap, ZaqarInternal, host]}
        zaqar::transport::wsgi::bind: {get_param: [EndpointMap, ZaqarInternal, host]}
        zaqar::management::mongodb::uri: mongodb://127.0.0.1:27017
        zaqar::messaging::mongodb::uri: mongodb://127.0.0.1:27017
        zaqar::db::mysql::password: {get_param: ZaqarPassword}
      step_config: |
        include ::tripleo::profile::base::zaqar
